version: '3.7'

services:
  database:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb
    restart: always
    tty: true
    ports:
      - 8081:8081
      - 8900:8900
      - 8901:8901
      - 8979:8979
      - 10250:10250
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
      - 10255:10255
      - 10256:10256
      - 10350:10350
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    networks:
      - eclipse
    volumes:
      - eclipse:/data

  backend:
    image: ${DOCKER_REGISTRY-}eclipse
    container_name: eclipse-webapi
    build: 
      context: ../
      dockerfile: Dockerfile
    environment:
    ports:
      - 7236:8080
    networks:
      - eclipse
    depends_on:
      - database

networks:
  eclipse:

volumes:
  eclipse:
