version: '3.9'

services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb
    restart: always
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE="cosmosdb"
    networks:
      - eclipse
    volumes:
      - eclipse:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:8081/_explorer/emulator.pem"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    
  cache:
    image: redis/redis-stack-server:latest
    container_name: eclipse-cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - eclipse:/cache
    networks:
      - eclipse
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

#git stash pop
  backend:
    image: ${DOCKER_REGISTRY-}eclipse
    container_name: eclipse-webapi
    build:
      context: ../
      dockerfile: Dockerfile
    
    ports:
      - 8080:8080
    networks:
      - eclipse
    depends_on:
      cosmosdb:
        condition: service_healthy
      cache:
        condition: service_healthy

networks:
  eclipse:
    driver: bridge

volumes:
  eclipse:
