version: '3.7'

services:
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    container_name: cosmosdb
    restart: always
    tty: true
    ports:
      - 8081:8081
      - 8900:8900
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    networks:
      - eclipse
    volumes:
      - eclipse:/data

  backend:
    image: ${DOCKER_REGISTRY-}eclipse
    container_name: eclipse-webapi
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - Azure__CosmosOptions__ConnectionString=
      - Telegram__Token=
      - Telegram__Chat=
      - Telegram__WebhookUrl=/api/eclipse/_handle
      - Telegram__SecretToken=my_Sup3r_S3cr3t_T0k3n
      - Authorization__EclipseApiKey=my_sup3r_s3cr3t_ap1_k3y
      - Google__ServiceApiKey=
      - 'Google__Credentials='
      - Sheets__SheetId=
      - Sheets__SuggestionsRange=
    ports:
      - 7236:7236
    networks:
      - eclipse
    depends_on:
      - cosmosdb

networks:
  eclipse:

volumes:
  eclipse:
