# For more info on HTTP files go to https://aka.ms/vs/httpfile

@page=1
@pageSize=5

GET https://{{hostname}}:{{port}}/api/users/list?page={{page}}&pageSize={{pageSize}}
X-Api-Version: {{apiVersion}}
X-Api-Key: {{apiKey}}
