
name: Development Container-based Build and deploy to an Azure

env:
  AZURE_WEBAPP_NAME: eclipse-prod-app
  DOTNET_VERSION: '8.0.*'
  DOTNET_CONFIGURATION: 'Release'

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ./Eclipse.WebAPI.sln

      - name: Build
        run: dotnet build ./Eclipse.WebAPI.sln --configuration ${{ env.DOTNET_CONFIGURATION }} --no-restore
        
      - name: Run tests
        run: dotnet test ./Eclipse.WebAPI.sln 
          --configuration ${{ env.DOTNET_CONFIGURATION }}
          --no-build
          --logger trx
          --results-directory ${{ github.workspace }}/test-results
          --collect "XPlat Code Coverage"

      - name: Generate test report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.8
        with:
          reports: ${{ github.workspace }}/test-results/**/*.xml
          targetdir: ${{ github.workspace }}/test-reports
          reporttypes: cobertura;Html_Dark
          tag: ${{ github.run_number }}_${{ github.run_id }}
      
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReports
          path: ${{ github.workspace }}/test-reports/Cobertura.xml

      - name: Publish test results
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'test-reports/Coverage.xml'
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '10 30'

  build-image:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:dev.${{ github.sha }}
          file: ./web-api.dockerfile

  deploy:
    if: github.ref_name == 'develop'
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-image
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROD_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:dev.${{ github.sha }}'
